def taglst(home_team, away_team):
    home_tag = []
    away_tag = []
    if home_team == 'CHE':
            home_tag = [
                '#cfc',
                '#chelsea',
                '#willian',
                '#hazard',
                '#chelseaindiasupportersclub',
                '#chelseafc',
                '#edenhazard',
                '#stamfordbridge',
                '#chelseaday',
                '#chelseafans',
                '#cfcindo',
                '#londonisblue',
                '#theblues',
                '#chelseanews',
                '#ctid',
                '#antonioconte',
                '#chelseatillidie',
                '#blueisthecolour',
                '#blueday',
                '#moda',
                '#londononly',
                '#londonforyo',
                '#blues',
                '#ktbffh',
                '#conte',
                '#coyb',
                '#chelseaworld',
                '#blueteam',
                '#foreverblue',
                '#comeonchelsea',
                '#prideoflondon',
                '#ktbffh',
                '#ifitsnotblueitwillbe',
                '#cfcarmy',
                '#theblues',
                '#comeonyoublues',
                '#wearechelsea']
    if away_team == 'CHE':
        away_tag = [
            '#cfc',
            '#chelsea',
            '#willian',
            '#hazard',
            '#chelseaindiasupportersclub',
            '#chelseafc',
            '#edenhazard',
            '#stamfordbridge',
            '#chelseaday',
            '#chelseafans',
            '#cfcindo',
            '#londonisblue',
            '#theblues',
            '#chelseanews',
            '#ctid',
            '#antonioconte',
            '#chelseatillidie',
            '#blueisthecolour',
            '#blueday',
            '#moda',
            '#londononly',
            '#londonforyo',
            '#blues',
            '#ktbffh',
            '#conte',
            '#coyb',
            '#chelseaworld',
            '#blueteam',
            '#foreverblue',
            '#comeonchelsea',
            '#prideoflondon',
            '#ktbffh',
            '#ifitsnotblueitwillbe',
            '#cfcarmy',
            '#theblues',
            '#comeonyoublues',
            '#wearechelsea']
    if home_team == 'MUN':
        home_tag = [
            '#mun',
            '#manchesterunited',
            '#mufc',
            '#ggmu',
            '#mourinho',
            '#davesaves',
            '#reddevils',
            '#red_devils',
            '#oldtrafford',
            '#manu',
            '#manchesterisred',
            '#manunited',
            '#busby',
            '#red_devils',
            '#mufcfamily',
            '#unitedtillidie',
            '#mufcfans',
            '#unitedfans',
            '#mufcfanpics',
            '#manutdfans',
            '#utd',
            '#redordead']
    if away_team == 'MUN':
        away_tag = [
            '#mun',
            '#manchesterunited',
            '#mufc',
            '#ggmu',
            '#mourinho',
            '#davesaves',
            '#reddevils',
            '#red_devils',
            '#oldtrafford',
            '#manu',
            '#manchesterisred',
            '#manunited',
            '#busby',
            '#red_devils',
            '#mufcfamily',
            '#unitedtillidie',
            '#mufcfans',
            '#unitedfans',
            '#mufcfanpics',
            '#manutdfans',
            '#utd',
            '#redordead']
    if home_team == 'MCI':
        home_tag = [
            '#mci',
            '#mancity',
            '#mcfc',
            '#manchester',
            '#manchestercity',
            '#mcfcofficial',
            '#manchestercityfc',
            '#mancityfc',
            '#guardiola',
            '#pepguardiola',
            '#bluemoon',
            '#fnh',
            '#ctid',
            '#mcwfc',
            '#blue']
    if away_team == 'MCI':
        away_tag = [
            '#mci',
            '#mancity',
            '#mcfc',
            '#manchester',
            '#manchestercity',
            '#mcfcofficial',
            '#manchestercityfc',
            '#mancityfc',
            '#guardiola',
            '#pepguardiola',
            '#bluemoon',
            '#fnh',
            '#ctid',
            '#mcwfc',
            '#blue']
    if home_team == 'LIV':
        home_tag = [
            '#lfc',
            '#ynwa',
            '#liverpool',
            '#nutmeg',
            '#reds',
            '#liverpoolproud',
            '#anfield',
            '#fort',
            '#ynwa',
            '#firmino',
            '#robertofirmino',
            '#lfcfamily',
            '#thereds',
            '#theredslfc',
            '#football',
            '#lfcfans',
            '#kloppsarmy',
            '#wegoagain',
            '#makeusdream',
            '#lovemyclub',
            '#yellowtshirt',
            '#thisisanfield',
            '#anfieldstadium',
            '#lallana',
            '#redmen',
            '#liverpoolfcfanclub',
            '#stevengerrard',
            '#youllneverwalkalone',
            '#jurgenklopp',
            '#liverpoolfans',
            '#ywnwa',
            '#gerrard',
            '#red',
            '#sakho',
            '#liverpoolfamily']
    if away_team == 'LIV':
        away_tag = [
            '#lfc',
            '#ynwa',
            '#liverpool',
            '#nutmeg',
            '#reds',
            '#liverpoolproud',
            '#anfield',
            '#fort',
            '#ynwa',
            '#firmino',
            '#robertofirmino',
            '#lfcfamily',
            '#thereds',
            '#theredslfc',
            '#football',
            '#lfcfans',
            '#kloppsarmy',
            '#wegoagain',
            '#makeusdream',
            '#lovemyclub',
            '#yellowtshirt',
            '#thisisanfield',
            '#anfieldstadium',
            '#lallana',
            '#redmen',
            '#liverpoolfcfanclub',
            '#stevengerrard',
            '#youllneverwalkalone',
            '#jurgenklopp',
            '#liverpoolfans',
            '#ywnwa',
            '#gerrard',
            '#red',
            '#sakho',
            '#liverpoolfamily']
    if home_team == 'TOT':
        home_tag = [
            '#tottenhamhotspur',
            '#coyg',
            '#tottenham',
            '#spurs',
            '#coys',
            '#ttid',
            '#thfc',
            '#yidarmy',
            '#tottenhamfc',
            '#totw',
            '#stadiumoflight',
            '#whitehartlane',
            '#tottenhamtillidie',
            '#comeonyouspurs',
            '#spursarmy',
            '#togetherthfc',
            '#spursfamily',
            '#spurs']
    if away_team == 'TOT':
        away_tag = [
            '#tottenhamhotspur',
            '#coyg',
            '#tottenham',
            '#spurs',
            '#coys',
            '#ttid',
            '#thfc',
            '#yidarmy',
            '#tottenhamfc',
            '#totw',
            '#stadiumoflight',
            '#whitehartlane',
            '#tottenhamtillidie',
            '#comeonyouspurs',
            '#spursarmy',
            '#togetherthfc',
            '#spursfamily',
            '#spurs']
    if home_team == 'EVE':
        home_tag = [
            '#coyb',
            '#toffees',
            '#upthetoffees',
            '#toonarmy',
            '#steventaylor',
            '#upontyne',
            '#stjamespark',
            '#stjames',
            '#everton',
            '#evertonfc',
            '#eagles',
            '#neverforgotten',
            '#seahouses',
            '#gerarddeulofeu',
            '#efc',
            '#brentford',
            '#evertonthe',
            '#morganschneiderlin',
            '#calcio',
            '#lukaku']
    if away_team == 'EVE':
        away_tag = [
            '#coyb',
            '#toffees',
            '#upthetoffees',
            '#toonarmy',
            '#steventaylor',
            '#upontyne',
            '#stjamespark',
            '#stjames',
            '#everton',
            '#evertonfc',
            '#eagles',
            '#neverforgotten',
            '#seahouses',
            '#gerarddeulofeu',
            '#efc',
            '#brentford',
            '#evertonthe',
            '#morganschneiderlin',
            '#calcio',
            '#lukaku']
    if home_team == 'ARS':
        home_tag = [
            '#gooner',
            '#ozil',
            '#gunners',
            '#westminster',
            '#arsenalfc',
            '#wengerout',
            '#coyg',
            '#afc',
            '#arsenal',
            '#gunners',
            '#arsenalfc',
            '#alexis',
            '#highbury',
            '#prideoflondon',
            '#emiratesstadium',
            '#wehatetottenham',
            '#arsene',
            '#wenger',
            '#londonisred',
            '#goonerette',
            '#yagoonersya',
            '#arsenalfantv']
    if away_team == 'ARS':
        away_tag = [
            '#gooner',
            '#ozil',
            '#gunners',
            '#westminster',
            '#arsenalfc',
            '#wengerout',
            '#coyg',
            '#afc',
            '#arsenal',
            '#gunners',
            '#arsenalfc',
            '#alexis',
            '#highbury',
            '#prideoflondon',
            '#emiratesstadium',
            '#wehatetottenham',
            '#arsene',
            '#wenger',
            '#londonisred',
            '#goonerette',
            '#yagoonersya',
            '#arsenalfantv']
    if home_team == 'LEI':
        home_tag = [
            '#lcfc',
            '#coyf',
            '#leicester',
            '#leicestercity',
            '#fuchs',
            '#foxes',
            '#foxesneverquit',
            '#lei',
            '#fearlessfoxes',
            '#mahrez',
            '#vardy',
            '#leicestertilidie',
            '#gofoxes',
            '#ranieri',
            '#bird',
            '#coys',
            '#comeonyoufoxes']
    if away_team == 'LEI':
        away_tag = [
            '#lcfc',
            '#coyf',
            '#leicester',
            '#leicestercity',
            '#fuchs',
            '#foxes',
            '#foxesneverquit',
            '#lei',
            '#fearlessfoxes',
            '#mahrez',
            '#vardy',
            '#leicestertilidie',
            '#gofoxes',
            '#ranieri',
            '#bird',
            '#coys',
            '#comeonyoufoxes']
    if home_team == 'WBA':
        home_tag = [
            '#wba',
            '#baggies',
            '#wbafc',
            '#westbrom',
            '#westbromwichalbionfc',
            '#ynwa',
            '#westbromfc',
            '#coyi',
            '#hawthorns',
            '#throstles']
    if away_team == 'WBA':
        away_tag = [
            '#wba',
            '#baggies',
            '#wbafc',
            '#westbrom',
            '#westbromwichalbionfc',
            '#ynwa',
            '#westbromfc',
            '#coyi',
            '#hawthorns',
            '#throstles']
    if home_team == 'SOU':
        home_tag = [
            '#saintsfc ',
            '#wemarchon',
            '#southamptonfc',
            '#saints',
            '#upthesaints',
            '#marchasone',
            '#ronaldkoeman',
            '#southampton',
            '#sfc',
            '#stmarys',
            '#koeman',
            '#redandwhite',
            '#wearesouthampton',
            '#josefonte',
            '#fonte',
            '#coyr',
            '#soares',
            '#redarmy',
            '#virgilvandijk']
    if away_team == 'SOU':
        away_tag = [
            '#saintsfc ',
            '#wemarchon',
            '#southamptonfc',
            '#saints',
            '#upthesaints',
            '#marchasone',
            '#ronaldkoeman',
            '#southampton',
            '#sfc',
            '#stmarys',
            '#koeman',
            '#redandwhite',
            '#wearesouthampton',
            '#josefonte',
            '#fonte',
            '#coyr',
            '#soares',
            '#redarmy',
            '#virgilvandijk']
    if home_team == 'SWA':
        home_tag = [
            '#swans',
            '#swanseacity',
            '#swansea',
            '#broadsideswansea',
            '#scfc',
            '#swanseacityfc',
            '#southwales',
            '#swan',
            '#sfc',
            '#safc',
            '#liberty',
            '#yjb',
            '#jackarmy']
    if away_team == 'SWA':
        away_tag = [
            '#swans',
            '#swanseacity',
            '#swansea',
            '#broadsideswansea',
            '#scfc',
            '#swanseacityfc',
            '#southwales',
            '#swan',
            '#sfc',
            '#safc',
            '#liberty',
            '#yjb',
            '#jackarmy']
    if home_team == 'CRY':
        home_tag = [
            '#cpfc',
            '#eagles ',
            '#crystalpalace',
            '#crystalpalacefc',
            '#coys',
            '#coyp',
            '#palace',
            '#calcio',
            '#southlondonandproud',
            '#official_cpfc ',
            '#bigsam',
            '#sam',
            '#saha',
            '#selhurst',
            '#glaziers']
    if away_team == 'CRY':
        away_tag = [
            '#cpfc',
            '#eagles ',
            '#crystalpalace',
            '#crystalpalacefc',
            '#coys',
            '#coyp',
            '#palace',
            '#calcio',
            '#southlondonandproud',
            '#official_cpfc ',
            '#bigsam',
            '#sam',
            '#saha',
            '#selhurst',
            '#glaziers']
    if home_team == 'SUN':
        home_tag = [
            '#safc',
            '#stadiumoflight',
            '#sunderland',
            '#sunderlandfc',
            '#defoe',
            '#blackcats',
            '#eastcoast',
            '#sun',
            '#light',
            '#moyes']
    if away_team == 'SUN':
        away_tag = [
            '#safc',
            '#stadiumoflight',
            '#sunderland',
            '#sunderlandfc',
            '#defoe',
            '#blackcats',
            '#eastcoast',
            '#sun',
            '#light',
            '#moyes']
    if home_team == 'STK':
        home_tag = [
            '#scfc',
            '#potters',
            '#bet365',
            '#stokecity',
            '#coymp',
            '#crouch',
            '#shaqiri',
            '#berahino',
            '#hughes']
    if away_team == 'STK':
        away_tag = [
            '#scfc',
            '#potters',
            '#bet365',
            '#stokecity',
            '#coymp',
            '#crouch',
            '#shaqiri',
            '#berahino',
            '#hughes']
    if home_team == 'Juve':
        home_tag = [
            '#juventus',
            '#gagliardini',
            '#juve',
            '#buongiornouncazzo',
            '#universita',
            '#mandzukic',
            '#trophy',
            '#juventusstadium',
            '#calciatoribrutti',
            '#ignoranza',
            '#fisica',
            '#fcjuventus',
            '#buffon',
            '#turin',
            '#juventusturin',
            '#dybala',
            '#danialves',
            '#higuain',
            '#paulodybala',
            '#alves',
            '#instajuve',
            '#ucl']
    if away_team == 'FCB':
        away_tag = [
            '#neymar',
            '#msn',
            '#bbc',
            '#suarez',
            '#leomessi',
            '#barcelona',
            '#pique',
            '#barca',
            '#championsleaguebarcelona',
            '#fcb',
            '#camp_nou',
            '#campnou',
            '#barcelonafc'
            '#real',
            '#barcelonetta',
            '#barcelonamenamora',
            '#barcellona',
            '#barcelonainspira',
            '#barcelonaexperience',
            '#barcelonagram', '#barcelonalovers', '#bcngram', '#espana',
            '#spain', '#catalunya', '#cataluna', '#bcnmoltes','#bcninspira', '#bcncolors,'
            '#empleo', '#barc', '#njr11', '#lm10', '#cr7']
    
    return home_tag, away_tag
